### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (668,460) (460,460) 

### ISSUE THREAD

**Issue by iairose** [moonfighting/PencilDrawing--python-version#1]
Traceback (most recent call last):
  File "./pencil_draw.py", line 181, in <module>
    res = pencil_drawing(img_path, pencil_texture)
  File "./pencil_draw.py", line 163, in pencil_drawing
    S = get_stroke(img, 3, 8)
  File "./pencil_draw.py", line 44, in get_stroke
    img_gredient = imX + imY
ValueError: operands could not be broadcast together with shapes (668,460) (460,460)

**Comment by murez** [comment]
I have a sample problem
fixing
QAQ

**Comment by murez** [comment]
I have fixed it


first err in the function 'get_stroke' :
```python
imX = np.append(np.absolute(img[:, 0: width - 1] - img[:, 1: width]), np.zeros((height, 1)), axis=1)
imY = np.append(np.absolute(img[0: height - 1, :] - img[1: height, :]), np.zeros((1, width)), axis=0)
```

second err in the 'function get_eight_directions' :
```python
y = int(half_len - int(round((x + 1 - half_len) * math.tan(math.pi * i / 8))))
```
some little err QAQ

**Comment by murez** [comment]
in my opinion this issue can close.

**Comment by caterZhong** [comment]
can you give the  color result code ?

**Comment by caterZhong** [comment]
the code only can use for picture which width is equal to height,  and the result is for from the matlab code
